apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
  - talker-api.127.0.0.1.nip.io
  identity:
  - name: a12n-server
    oauth2:
      tokenIntrospectionUrl: http://a12n-server.a12n-server.svc.cluster.local:8531/introspect
      credentialsRef:
        name: oauth2-token-introspection-credentials
  authorization:
  - name: can-read
    json:
      rules:
        - selector: auth.identity.privileges.talker-api
          operator: incl
          value: read
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-token-introspection-credentials
stringData:
  clientID: talker-api
  clientSecret: V6g-2Eq2ALB1_WHAswzoeZofJ_e86RI4tdjClDDDb4g
type: Opaque
