apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-consumer-1
---
apiVersion: v1
kind: Pod
metadata:
  name: api-consumer
spec:
  containers:
  - name: api-consumer
    image: quay.io/3scale/authorino-examples:api-consumer
    command: ["./run"]
    args:
    - --endpoint=http://envoy.authorino.svc.cluster.local:8000/hello
    - --token-path=/var/run/secrets/tokens/api-token
    - --interval=10
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: talker-api-access-token
  serviceAccountName: api-consumer-1
  volumes:
  - name: talker-api-access-token
    projected:
      sources:
      - serviceAccountToken:
          path: api-token
          expirationSeconds: 7200
          audience: talker-api
