#!/bin/bash

interval="10"
credentialsIn="authorization_header"
credentialsKey="Bearer"

curl_cmd="curl "

while [[ $# -gt 0 ]]; do
  key=${1%=*}
  val=${1#*=}

  case $key in
    --endpoint )
      endpoint="$val"
      ;;
    --token )
      token="$val"
      ;;
    --token-path )
      token=$(cat "$val")
      ;;
    --credentials-in )
      credentialsIn="$val"
      ;;
    --credentials-key )
      credentialsKey="$val"
      ;;
    --interval )
      interval="$val"
      ;;
    --debug )
      DEBUG="true"
      ;;
    --* )
      curl_cmd+="$key "
      if [[ "$key" != "$val" ]]; then
        curl_cmd+="$val "
      fi
      ;;
    * )
      ;;
  esac

  shift
done

if [ "$credentialsIn" == "authorization_header" ]; then
  curl_cmd+="-H \"Authorization: $credentialsKey $token\" "
elif [ "$credentialsIn" == "custom_header" ]; then
  curl_cmd+="-H \"${credentialsKey}: $token\" "
elif [ "$credentialsIn" == "cookie" ]; then
  curl_cmd+="-H \"Cookie: $credentialsKey=$token\" "
elif [ "$credentialsIn" == "query" ]; then
  endpoint="$endpoint?$credentialsKey=$token"
fi

curl_cmd+=" \"$endpoint\""

if [ "$DEBUG" == "true" ]; then
  echo "Command:  $curl_cmd"
  echo "Interval: $interval"
  echo ""
fi

echo "Sending..."

while true; do
  eval $curl_cmd
  echo ""
  if [ "$interval" == "0" ]; then
    exit 0
  fi
  sleep $interval
done
