apiVersion: apps/v1
kind: Deployment
metadata:
  name: a12n-server-mysql
  labels:
    app: a12n-server
spec:
  selector:
    matchLabels:
      app: a12n-server-mysql
  template:
    metadata:
      labels:
        app: a12n-server-mysql
    spec:
      containers:
      - name: mysql
        image: quay.io/3scale/authorino-examples:a12n-server-mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: a12n-server-mysql
spec:
  selector:
    app: a12n-server-mysql
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a12n-server
  labels:
    app: a12n-server
spec:
  selector:
    matchLabels:
      app: a12n-server
  template:
    metadata:
      labels:
        app: a12n-server
    spec:
      containers:
      - name: a12n-server
        image: quay.io/3scale/authorino-examples:a12n-server
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: a12n-server-mysql
        - name: MYSQL_DATABASE
          value: a12nserver
        - name: MYSQL_USER
          value: a12nserver
        - name: MYSQL_PASSWORD
          value: secret
        ports:
        - containerPort: 8531
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: a12n-server
spec:
  selector:
    app: a12n-server
  ports:
    - port: 8531
      protocol: TCP
