apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
  - talker-api.127.0.0.1.nip.io
  identity:
  - name: api-clients
    apiKey:
      selector:
        matchLabels:
          group: friends
    credentials:
      in: authorization_header
      keySelector: APIKEY
