apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.22
        args:
        - "--collector.zipkin.host-port=:9411"
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 5778
          name: configs
        - containerPort: 16686
          name: server-frontend
        - containerPort: 14250
          name: collector-grpc
        - containerPort: 14268
          name: collector-trft
        - containerPort: 9411
          name: zk-collector
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 5775
    name: zk-compact-trft
    protocol: UDP
  - port: 6831
    name: jg-compact-trft
    protocol: UDP
  - port: 6832
    name: jg-binary-trft
    protocol: UDP
  - port: 5778
    name: configs
    protocol: TCP
  - port: 16686
    name: server-frontend
    protocol: TCP
  - port: 14250
    name: collector-grpc
    protocol: TCP
  - port: 14268
    name: collector-trft
    protocol: TCP
  - port: 9411
    name: zk-collector
    protocol: TCP
