apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.43
        args:
        - --collector.otlp.enabled=true
        - --collector.otlp.grpc.host-port=:14251
        - --collector.otlp.http.host-port=:9412
        - --collector.zipkin.host-port=:9411
        ports:
        - name: zk-compact-trft
          containerPort: 5775
          protocol: UDP
        - name: jg-compact-trft
          containerPort: 6831
          protocol: UDP
        - name: jg-binary-trft
          containerPort: 6832
          protocol: UDP
        - name: configs
          containerPort: 5778
        - name: server-frontend
          containerPort: 16686
        - name: collector-grpc
          containerPort: 14250
        - name: collector-trft
          containerPort: 14268
        - name: otlp-grpc
          containerPort: 14251
        - name: otlp-http
          containerPort: 9412
        - name: zk-collector
          containerPort: 9411
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
  - name: configs
    port: 5778
    protocol: TCP
  - name: server-frontend
    port: 16686
    protocol: TCP
  - name: collector-grpc
    port: 14250
    protocol: TCP
  - name: collector-trft
    port: 14268
    protocol: TCP
  - name: otlp-grpc
    port: 14251
    protocol: TCP
  - name: otlp-http
    port: 9412
    protocol: TCP
  - name: zk-collector
    port: 9411
    protocol: TCP
